In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Data = {'Year': [1920,1930,1940,1950,1960,1970,1980,1990,2000, 2010, 2020],
       'Exchange Rate': [65, 69, 71, 64, 62, 59, 72, 71, 75, 78, 81]}

In [3]:
type(Data)

dict

In [4]:
Data

{'Year': [1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020],
 'Exchange Rate': [65, 69, 71, 64, 62, 59, 72, 71, 75, 78, 81]}

In [10]:
df = pd.DataFrame(Data)

In [6]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.head(5)

   Year  Exchange Rate
0  1920             65
1  1930             69
2  1940             71
3  1950             64
4  1960             62

In [12]:
df = pd.DataFrame(Data, columns = ['Year', 'Exchange Rate'])

In [13]:
df.head(5)

   Year  Exchange Rate
0  1920             65
1  1930             69
2  1940             71
3  1950             64
4  1960             62

In [14]:
type(df)

pandas.core.frame.DataFrame